### PR TITLE
Update to 1.16.2

### PR DESCRIPTION
**Pull request by Wybranowsky**
update NBT api

### CODE REVIEW

**Comment by Wybranowsky** [comment]
[Download working build](https://cdn.discordapp.com/attachments/472015002153386004/745594715423899744/DeluxeHub-1.16.2.jar)

**Review by mtatko — APPROVED** [review]
working fine 100%

**Comment by ItsLewizzz** [comment]
Thanks for this :)

**Comment by WolverStones** [comment]
I tried it but I can't confirm the functionality of custom join items, if I join I won't get any item.

**Pull request merged**
