### PR TITLE
Add 1.21.1 support

### PR DESCRIPTION
**Pull request by Strafbefehl**

### CODE REVIEW

**Comment by BeholdIsLost** [comment]
It dosent have 1.21.1 .jar file as in release to download

**Comment by TutorialMan7727** [comment]
I assume when the pr gets merged, the owner will compile and add to the releases tab but for now you will have to compile it yourself

**Comment by Strafbefehl** [comment]
> It dosent have 1.21.1 .jar file as in release to download

Check this out :)
https://github.com/Strafbefehl/DeluxeHubReloaded/releases/tag/Release

**Comment by TutorialMan7727** [comment]
@Strafbefehl you acadently pushed the rest of that repo to this pr. You might have to close it so it doesnt get merged

**Comment by Strafbefehl** [comment]
Thanks @TutorialMan7727

**Pull request closed without merging**
